/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Posts a signed data item to arweave */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A signed data item */
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description The signed data item was successfully submitted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataItemPost"];
                    };
                };
                /** @description Invalid data item post */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Insufficient balance */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tx/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Posts a signed data item to arweave for a specific token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: "arweave" | "ethereum" | "solana" | "ario" | "base-eth";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description The receipt of the uploaded data item. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataItemPost"];
                    };
                };
                /** @description Insufficient balance */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DataItemPost: {
            /**
             * @description The id of the data item.
             * @example QpmY8mZmFEC8RxNsgbxSV6e36OF6quIYaPRKzvUco0o
             */
            id?: string;
            /**
             * @description The normalized wallet address that signed data item.
             * @example 8wgRDgvYOrtSaWEIV21g0lTuWDUnTu4_iYj4hmA7PI0
             */
            owner?: string;
            /**
             * @description The Arweave data caches the data item has been posted to.
             * @example [
             *       "arweave.net"
             *     ]
             */
            dataCaches?: string[];
            /**
             * @description The Arweave fast finality indexes the data item has been posted to.
             * @example [
             *       "arweave.net"
             *     ]
             */
            fastFinalityIndexes?: string[];
            /**
             * @description The deadline block height for the data item to be posted to Arweave.
             * @example 1310000
             */
            deadlineHeight?: number;
            /**
             * @description The timestamp in millisecond of when the data item was fully uploaded and receipt was signed.
             * @example 1700590909589
             */
            timestamp?: number;
            /**
             * @description The version of the receipt
             * @example 0.1.0
             */
            version?: string;
            /** @description The base64URL signature of the receipt. */
            signature?: string;
            /** @description The public key of the wallet that signed the receipt */
            public?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
